# -*- coding: utf-8 -*-
"""Week 4 ModSim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14RuylAF7enz-hNwZJ0T1VnLcxE0h5oUJ
"""

import time
import threading
import numpy as np
import random

class Person(threading.Thread):
    def _init_(self, name, delay, status, amount):
        threading.Thread.__init__(self)
        self.name = name
        self.delay = delay
        self.status = stat
        self.amount = amnt

def run(self):
        acc = 2000
        for i in range(10):
            saveOrWithdraw = random.randint(0,1)
            if saveOrWithdraw == 1:
                acc = acc + self.amnt
                print(self.name + 'has saved: ' + self.amnt + 'into bank account with balance: ' + acc)
                time.sleep(abs(self.delay))

            else:
                acc = acc - self.amnt
                print(self.name + 'has withdrawn:' + self.amnt + 'from bank account with balance:' + acc )
                time.sleep(abs(self.delay))

p1 = Person("Abu", 2, random.randint(0, 1), np.random.randint(52, 200))
p2 = Person('Ali', 1, random.randint(0, 1), np.random.randint(16, 400))
p3 = Person('Aiman', 3, np.random.randint(0, 1), np.random.randint(30, 40))

p1.start()
p2.start()
p3.start()
p1.join()
p2.join()
p3.join()


print('Exiting Thread...')